# Generated by Django 3.1.7 on 2021-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofile', '0002_auto_20210612_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_introduction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
