# Generated by Django 3.1.7 on 2021-06-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofile', '0004_auto_20210612_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BOD',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.TextField(blank=True),
        ),
    ]
