# Generated by Django 3.1.7 on 2021-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofile', '0006_auto_20210612_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BOD',
            field=models.DateField(null=True),
        ),
    ]
