# Generated by Django 3.2.3 on 2021-06-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
