# Generated by Django 3.2.3 on 2021-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_forum', '0002_discussion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='mood',
            field=models.CharField(choices=[['Happy', 'Happy'], ['Angry', 'Angry'], ['Sad', 'Sad']], default='No Feelings', max_length=50),
        ),
    ]
