# Generated by Django 3.2.3 on 2021-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitforum', '0003_remove_video_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='People who are unwilling to reveal their identity', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='People who are unwilling to reveal their identity', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=200),
        ),
    ]
