# Generated by Django 3.2.3 on 2021-06-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitforum', '0004_auto_20210609_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
