# Generated by Django 3.1.7 on 2021-05-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210518_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='(empty)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
