# Generated by Django 3.2.3 on 2021-06-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('contribution', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('card_type', models.CharField(choices=[('day', 'Recipes_of_the_day'), ('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], default='day', max_length=100)),
                ('time_to_cook', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredients', models.TextField()),
                ('prep_method', models.TextField()),
            ],
        ),
    ]
