# Generated by Django 3.2.3 on 2021-06-05 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_food_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
