# Generated by Django 3.1.7 on 2021-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message_subject',
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_name',
            field=models.CharField(default='(No Name)', max_length=50),
        ),
    ]
