# Generated by Django 3.1.7 on 2021-06-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210611_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_subject2',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='contact.message_subject_2'),
        ),
    ]
